### ISSUE TITLE
Invalid LOC Header

### ISSUE THREAD

**Issue by AppeazeTheCheese** [TheBlackEntity/PlugMan#16]
Starting today I've been getting this strange error. Even stranger is the plugin was working fine yesterday, and as far as I know nothing has changed. I've restarted the server twice to no avail. I've ensured all the YML configs are UTF-8 encoded, and even re-downloaded the plugin from the website but nothing has changed.

The full error message (first line of the stacktrace) is as follows:
`org.yaml.snakeyaml.error.YAMLException: java.util.zip.ZipException: ZipFile invalid LOC header (bad signature)`

Here's my full log: https://mclo.gs/JMZu5Y5

**Comment by TheBlackEntity** [comment]
You have quite a few error messages...

Since ProtocolLib has the same issue, I'm unsure if this is a PlugManX specific issue.

I will try to do some testing on my end though.



Can you please tell me your Java version?

**Comment by AppeazeTheCheese** [comment]
Yeah we recently updated to Minecraft version 1.20 which is why there is a lot of errors. I've slowly been going through and fixing them. We are running Java JDK 17.

**Comment by AppeazeTheCheese** [comment]
I just re-installed ProtocolLib and it seems to have fixed both plugins, which is strange to me because as far as I can tell this plugin doesn't use ProtocolLib.
